### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by parksb** [parksb/handmade-blog#13]
* Need to make the tutorials in the README document more effective.
* Fix incorrect words and typos.

**Comment by Annysah** [comment]
Hello,
I would like to know what you mean by making the  tutorial more effective?

**Comment by parksb** [comment]
> Hello,
> I would like to know what you mean by making the tutorial more effective?

Currently, 'Usage' and 'Available Scripts' paragraphs are a little unfriendly. I think the paragraphs have to provide more information for newbies.

**Comment by Annysah** [comment]
Oh, great!
I would like to work on this but how can I get more informations to be provided in the docs?

**Comment by fritssasia** [comment]
Can I contribute by translating the documentation into Indonesian language?
I will create a file called `README-IND.md` (containing the documentation that I have translated into Indonesian)
and slightly modified the `README.md` file by adding menu `documentation in several languages`

I think this will be very helpful for some people who can't speak english

**Comment by parksb** [comment]
> Oh, great!
> I would like to work on this but how can I get more informations to be provided in the docs?

* In the 'Project structure' paragraph, there are `classes` and `models` directories with no descriptions. I recommend writing a description to them.
* The 'Available Scripts' paragraph describes some scripts with just one line sentences. I think it can be more verbose. You can check some scripts in [package.json](https://github.com/parksb/handmade-blog/blob/master/package.json) file and [tools](https://github.com/parksb/handmade-blog/tree/master/tools) directory.

Please comment on this issue if you have any questions. Thank you :)

**Comment by parksb** [comment]
> Can I contribute by translating the documentation into Indonesian language?
> I will create a file called `README-IND.md` (containing the documentation that I have translated into Indonesian)
> and slightly modified the `README.md` file by adding menu `documentation in several languages`
> 
> I think this will be very helpful for some people who can't speak english

Sounds good!

**Comment by fritssasia** [comment]
> > Can I contribute by translating the documentation into Indonesian language?
> > I will create a file called `README-IND.md` (containing the documentation that I have translated into Indonesian)
> > and slightly modified the `README.md` file by adding menu `documentation in several languages`
> > I think this will be very helpful for some people who can't speak english
> 
> Sounds good!

Thank you, so can I contribute by translating this documentation into Indonesian language? :"

**Comment by parksb** [comment]
> > > Can I contribute by translating the documentation into Indonesian language?
> > > I will create a file called `README-IND.md` (containing the documentation that I have translated into Indonesian)
> > > and slightly modified the `README.md` file by adding menu `documentation in several languages`
> > > I think this will be very helpful for some people who can't speak english
> > 
> > 
> > Sounds good!
> 
> Thank you, so can I contribute by translating this documentation into Indonesian language? :"

Yup! Please write `README-IND.md` document :)

**Comment by fritssasia** [comment]
> > > > Can I contribute by translating the documentation into Indonesian language?
> > > > I will create a file called `README-IND.md` (containing the documentation that I have translated into Indonesian)
> > > > and slightly modified the `README.md` file by adding menu `documentation in several languages`
> > > > I think this will be very helpful for some people who can't speak english
> > > 
> > > 
> > > Sounds good!
> > 
> > 
> > Thank you, so can I contribute by translating this documentation into Indonesian language? :"
> 
> Yup! Please write `README-IND.md` document :)

thank you very much, i will make it
and I will also try to invite some friends who might help translate this documentation into several languages. I hope this helps
