### ISSUE TITLE
parcel build not working

### ISSUE THREAD

**Issue by raydog99** [parksb/handmade-blog#43]
Running 'npm run build' results in a few errors in the compressed files. Namely, the html files in /dist result in "ERR_FILE_NOT_FOUND" as they try to find each other. 

It looks like "parcel build" has an issue with relative assets: https://github.com/parcel-bundler/parcel/issues/206

A partial solution is, on line 44 in tools/build.sh, add: "--public-url ./"

But the files in articles and work still have the relative path error. Not sure how others haven't run into this issue.

**Comment by raydog99** [comment]
My guess is `parcel build` expects all files to be in the same directory, but article and work end up as child directories in /dist. 

Ex: dist/article/0.html will look for navigation.html as './navigation.html' when it should be looking at '../navigation.html'. I couldn't find ways for parcel to fix this. 

One workaround is to just write a script that fixes the paths in child directories:

```
from os import listdir
from os.path import isfile, join
import fileinput
from bs4 import BeautifulSoup

def path_replace(src_dir):
	files = [f for f in listdir(src_dir) if isfile(join(src_dir, f)) and f.endswith('.html')]

	for single_file in files:
		soup = BeautifulSoup(open(src_dir + single_file), 'html.parser')

		links = soup.find_all(href=True)
		links = list(filter(lambda x: x['href'].endswith(('.css', '.ico', '.html', '.js')), links))

		for link in links:
			link['href'] = '../' + link['href']

		src_links = soup.find_all(src=True)
		src_links = list(filter(lambda x: x['src'].endswith(('.css', '.ico', '.html', '.js')), src_links))

		for link in src_links:
			link['src'] = '../' + link['src']


		with open(src_dir + single_file, 'w') as fp:
			fp.write(soup.prettify())


dirs = ['dist/article/', 'dist/work/']
for folder in dirs:
	path_replace(folder)
```

You can automate this by adding `python3 tools/path_replacer.py` at the bottom of tools/build.sh. 

In articles.ejs, works.ejs, replace the navigation header element with the code in navigation.ejs and replace the header-id from "top-container" to "nav-styling". Copy the code in navigation.scss to the bottom of init.scss, renaming "top-container" to "nav-styling".

This is not the ideal solution, so leaving this open until someone finds the right way to use parcel to resolve it.

**Comment by parksb** [comment]
I just removed parcel from this project. Thank you for reporting.
