### ISSUE TITLE
Inquiry about how to change the blog text font

### ISSUE THREAD

**Issue by YuHoChau** [parksb/handmade-blog#46]
Hi,
I met some troubles in changing the text font. I wonder if it is possible for you to provide a simple tutorial? 
> app: assets - Any files to be imported by HTML files such as image, font, etc.
I failed to find the right path/method to change the default setting. 

Thank you for your help :)

**Comment by hey-rum-ba** [comment]
Hi there,
I wonder whether you are using HTML 5 as there will be no font option available for changing font styles and sizes, you can do so by CSS itself. here is a link you might find useful -> [W3 school CSS Font](https://www.w3schools.com/css/css_font.asp)

**Comment by YuHoChau** [comment]
Hi,
Thank you for your reply. My question is that how can I just change the default font of this template? I understand that the CSS could change the styles of HTML, yet I could not find the CSS file for this template.
More specifically, what I want to realize is just simply change the text font of articles in this blog, and I don't know which file should be modified and how.

Apologize that I don't have much experience in front-end development XD, thank you again for your help.

**Comment by hey-rum-ba** [comment]
Hello, 
Thanks for elaborating your concern, as I can see you are unable to detect the parent CSS file, still you can change the font through InLineCSS for example
`<h1 style="color:blue; text-align:center; font-family:Times; font-size:40px">This is a heading</h1>
<p style="color:red;">This is a paragraph.</p>`   
as Inline-styles are defined within the "style" attribute of the relevant element.

**Comment by hey-rum-ba** [comment]
<h1 style="color:blue; text-align:center; font-family:Arial; font-size:40px">This is a heading</h1>
<p style="color:red;">This is a paragraph.</p> 
it was the code used here.

**Comment by YuHoChau** [comment]
Thank you so much. I'll take a try.

**Comment by hey-rum-ba** [comment]
``` 
<h1 style="color:blue; text-align:center; font-family:Arial; font-size:40px">This is a heading</h1>
<p style="color:red;">This is a paragraph.</p>
