### ISSUE TITLE
`npm run watch` does not work

### ISSUE THREAD

**Issue by thebbong** [parksb/handmade-blog#54]
사용해보려는데, npm run watch후 다른 터미널에서 npm start해도
watch쪽에서 Watch changes...로 변경감지는 되는데 local이 변경은 안되네요. 그래서 article수정하고 그때마다 npm run build로 변경된거를 확인하는데, 원래 이런가 해서요.

**Comment by parksb** [comment]
버그입니다. 서버가 바라보는 디렉토리 경로가 잘못되어 있는 것 같아요. 빠르게 수정하도록 하겠습니다. 제보해주셔서 감사합니다 :)

(+) 다른 사용자들도 이해할 수 있도록 이슈 제목을 영어로 변경했습니다.

**Comment by parksb** [comment]
https://github.com/parksb/handmade-blog/commit/4e008ce6bd10249965d061ec5a499575fa563281 커밋에서 수정했습니다.
